"""empty message

Revision ID: 01d59557ba93
Revises: 66a99eeeb9f6
Create Date: 2023-05-23 20:49:57.488961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01d59557ba93'
down_revision = '66a99eeeb9f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
