"""empty message

Revision ID: 09b7580fa1a5
Revises: 3e2ffa76f8b7
Create Date: 2023-05-23 19:29:47.030566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09b7580fa1a5'
down_revision = '3e2ffa76f8b7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
