"""Add new updates

Revision ID: 2320763592c9
Revises: f4ef80c81abc
Create Date: 2023-05-23 19:22:15.673209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2320763592c9'
down_revision = 'f4ef80c81abc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
