"""empty message

Revision ID: 25d760a0517a
Revises: 59ba554903eb
Create Date: 2023-05-23 19:12:11.653257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25d760a0517a'
down_revision = '59ba554903eb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
