"""new

Revision ID: 3e2ffa76f8b7
Revises: 2320763592c9
Create Date: 2023-05-23 19:25:05.397161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e2ffa76f8b7'
down_revision = '2320763592c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users',
    sa.Column('password', sa.String(100), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
