"""empty message

Revision ID: 65223f667816
Revises: 9c7a3ff31581
Create Date: 2023-05-24 14:44:16.642447

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Table, MetaData
from db.db_setup import Base

import os 
import json

# revision identifiers, used by Alembic.
revision = '65223f667816'
down_revision = '9c7a3ff31581'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('price', sa.Float(), nullable=False))

    metadata = Base.metadata

    metadata.bind = op.get_bind()

    movies = Table('course', metadata)

    with open(os.path.join(os.path.dirname(__file__) , "../data/courses.json" ) , encoding='utf-8' ) as f:
        course_data = f.read()

    op.bulk_insert(movies , json.loads(course_data))  
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'price')
    # ### end Alembic commands ###
