"""empty message

Revision ID: 66a99eeeb9f6
Revises: 09b7580fa1a5
Create Date: 2023-05-23 19:35:17.858749

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '66a99eeeb9f6'
down_revision = '09b7580fa1a5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(length=45),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=45),
               existing_nullable=False)
    # ### end Alembic commands ###
