"""empty message

Revision ID: bfc15aae2e46
Revises: 25d760a0517a
Create Date: 2023-05-23 19:15:40.018579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfc15aae2e46'
down_revision = '25d760a0517a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
