"""empty message

Revision ID: df9dca664ef3
Revises: 01d59557ba93
Create Date: 2023-05-23 20:51:19.420930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df9dca664ef3'
down_revision = '01d59557ba93'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('language', sa.String(length=45), nullable=False),
    sa.Column('course_lenght', sa.String(length=45), nullable=False),
    sa.Column('course_capacity', sa.Integer(), nullable=False),
    sa.Column('is_special', sa.Boolean(), nullable=False),
    sa.Column('level', sa.String(length=45), nullable=True),
    sa.Column('level_number', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_course',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_course')
    op.drop_table('course')
    # ### end Alembic commands ###
