"""empty message

Revision ID: f4ef80c81abc
Revises: bfc15aae2e46
Create Date: 2023-05-23 19:20:36.646827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4ef80c81abc'
down_revision = 'bfc15aae2e46'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
