"""empty message

Revision ID: 8de70d6d41f2
Revises: 
Create Date: 2023-05-05 18:55:04.712554

"""
from alembic import op
import sqlalchemy as sa

import os 
import json


# revision identifiers, used by Alembic.
revision = '8de70d6d41f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    movies = op.create_table('movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('year', sa.String(length=10), nullable=False),
    sa.Column('plot', sa.Text(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('poster', sa.Text(), nullable=True),
    sa.Column('director', sa.Text(), nullable=False),
    sa.Column('actors', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )




    op.create_index(op.f('ix_movie_actors'), 'movie', ['actors'], unique=False)
    op.create_index(op.f('ix_movie_director'), 'movie', ['director'], unique=False)
    op.create_index(op.f('ix_movie_id'), 'movie', ['id'], unique=False)
    op.create_index(op.f('ix_movie_plot'), 'movie', ['plot'], unique=False)
    op.create_index(op.f('ix_movie_poster'), 'movie', ['poster'], unique=False)
    op.create_index(op.f('ix_movie_rank'), 'movie', ['rank'], unique=True)
    op.create_index(op.f('ix_movie_title'), 'movie', ['title'], unique=False)
    op.create_index(op.f('ix_movie_year'), 'movie', ['year'], unique=False)

    with open(os.path.join(os.path.dirname(__file__) , "../data/movies.json")) as f:
        movies_data = f.read()

    op.bulk_insert(movies , json.loads(movies_data))    


    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('userName', sa.String(length=100), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_full_name'), 'users', ['full_name'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_password'), 'users', ['password'], unique=True)
    op.create_index(op.f('ix_users_userName'), 'users', ['userName'], unique=True)


    op.create_table('favourit_movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_favourit_movies_id'), 'favourit_movies', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_favourit_movies_id'), table_name='favourit_movies')
    op.drop_table('favourit_movies')
    op.drop_index(op.f('ix_users_userName'), table_name='users')
    op.drop_index(op.f('ix_users_password'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_full_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_movie_year'), table_name='movie')
    op.drop_index(op.f('ix_movie_title'), table_name='movie')
    op.drop_index(op.f('ix_movie_rank'), table_name='movie')
    op.drop_index(op.f('ix_movie_poster'), table_name='movie')
    op.drop_index(op.f('ix_movie_plot'), table_name='movie')
    op.drop_index(op.f('ix_movie_id'), table_name='movie')
    op.drop_index(op.f('ix_movie_director'), table_name='movie')
    op.drop_index(op.f('ix_movie_actors'), table_name='movie')
    op.drop_table('movie')
    # ### end Alembic commands ###
