"""Add new table

Revision ID: f2d86a63557d
Revises: 8de70d6d41f2
Create Date: 2023-05-06 11:48:12.276015

"""
from alembic import op
import sqlalchemy as sa
import os , json


# revision identifiers, used by Alembic.
revision = 'f2d86a63557d'
down_revision = '8de70d6d41f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
